'use client';
import { createTopicPages, type TopicPageSpec } from './topic-page';
const specs: TopicPageSpec[] = [
  {id:'solid',chapter:'Design principles',title:'SOLID in practical Java design',answer:'SOLID encourages cohesive responsibilities, extension through stable abstractions, substitutable implementations, focused interfaces, and dependencies directed toward policies rather than concrete infrastructure.',sections:[{title:'Use as diagnostic questions',bullets:['Does this class change for unrelated reasons?','Can a subtype honor every promise of its base type?','Does a client depend on methods it never uses?','Can business policy be tested without constructing infrastructure?']}]},
  {id:'composition',chapter:'Design principles',title:'Composition before inheritance',answer:'Composition delegates work to collaborators and can vary behavior without pretending one type is another. Inheritance is appropriate for a true substitutable relationship with a stable base contract.',callout:{title:'Why composition is safer',text:'It reduces coupling to protected state and base-class lifecycle, and avoids fragile overrides that violate expectations.'}},
  {id:'architecture-styles',chapter:'Architecture styles',title:'Layered, hexagonal, and clean architecture',answer:'Layered architecture groups UI, application, domain, and infrastructure. Hexagonal architecture puts use cases at the center and connects external systems through ports and adapters. Clean architecture similarly directs dependencies inward toward policy.',flow:['External adapter','Port interface','Application use case','Domain policy'],sections:[{title:'The useful rule',text:'Business rules should not require a web server or database to execute. The number and names of circles matter less than dependency direction.'}]},
  {id:'ddd',chapter:'Domain modeling',title:'Bounded contexts, aggregates, and value objects',answer:'A bounded context defines where a domain model and language are valid. An aggregate is a consistency boundary changed through one root. A value object is defined by its values and is usually immutable.',sections:[{title:'Boundary consequences',text:'Do not create one enterprise-wide object model. Translate between contexts, keep synchronous invariants inside an aggregate, and coordinate across aggregates explicitly.'}]},
  {id:'creational-behavioral',chapter:'Java patterns',title:'Strategy, Factory, and Builder',answer:'Strategy selects interchangeable behavior. Factory centralizes creation decisions. Builder assembles a complex object clearly, especially with optional values and validation.',comparisons:[{title:'Strategy',text:'Inject PricingPolicy rather than branching on a type throughout the code.'},{title:'Factory',text:'Choose and construct the correct adapter from configuration or input.'},{title:'Builder',text:'Name arguments and validate construction without telescoping constructors.'}]},
  {id:'structural',chapter:'Java patterns',title:'Adapter, Decorator, Proxy, and Observer',answer:'Adapter translates one interface to another. Decorator adds behavior while preserving an interface. Proxy controls access to another object. Observer notifies subscribers when something changes.',sections:[{title:'Similar shape, different intent',text:'A decorator adds responsibility; a proxy controls access or remoteness. Spring transaction proxies wrap calls without changing the service interface. Domain events are a form of observation but need explicit delivery semantics across processes.'}]},
  {id:'repository-uow',chapter:'Persistence patterns',title:'Repository and Unit of Work',answer:'A repository presents collection-like access to aggregates and hides persistence mechanics. A Unit of Work tracks changes and commits them as one transaction. JPA EntityManager and persistence context provide much of this behavior.',callout:{title:'Avoid abstraction theater',text:'A repository that mirrors every ORM method adds indirection without protecting a domain boundary.'}},
  {id:'pattern-cost',chapter:'Design judgment',title:'When patterns add unnecessary complexity',answer:'A pattern is useful when it names and stabilizes a recurring variation or boundary. It is harmful when it predicts flexibility that never arrives, scatters simple behavior, or hides the execution path.',sections:[{title:'Decision test',bullets:['What concrete change or dependency does it isolate?','Is there more than one implementation or a credible near-term need?','Can a simpler function or class express it?','Will the next engineer find behavior more easily?']}]},
  {id:'coupling',chapter:'Design quality',title:'Coupling and cohesion',answer:'Cohesion means related behavior and data live together. Coupling means one module depends on details of another. Aim for high cohesion and explicit, stable coupling—not zero coupling, which is impossible in a useful system.',sections:[{title:'Measure symptoms',text:'Changes touching many modules, cyclic dependencies, shared mutable data, and mocks for every internal call signal poor boundaries.'}]},
  {id:'adrs-debt',chapter:'Architecture practice',title:'ADRs and technical debt',answer:'An architecture decision record captures context, decision, alternatives, consequences, and status. Technical debt should be prioritized by business risk and recurring cost, not by aesthetic dislike.',sections:[{title:'Prioritize debt',bullets:['Production risk or security exposure','Delivery delay and repeated defects','Operational toil and ownership confusion','Cost of delay versus cost and risk of remediation']}]},
  {id:'legacy',chapter:'Evolution',title:'Refactoring a legacy system safely',answer:'Create a safety net around observable behavior, identify a narrow seam, make a small reversible change, release it, and measure. Use branch-by-abstraction or a strangler approach for longer migrations.',flow:['Characterize behavior','Introduce seam','Move one path','Verify and remove old path'],callout:{title:'Keep changes releasable',text:'Separate structural refactoring from behavior changes when possible so failures are easier to attribute and roll back.'}},
  {id:'patterns-recap',chapter:'Daily recap',title:'Architecture and patterns checklist',answer:'Start with the problem and boundary, then select the smallest pattern that makes change safer. Explain its cost and how the design can evolve.',sections:[{title:'Interview close',bullets:['Name intent, not only pattern structure.','Give a concrete Java or production example.','Explain the alternative you rejected.','Connect the choice to cohesion, coupling, testing, and operations.']}],links:[{label:'Microsoft architecture styles',href:'https://learn.microsoft.com/azure/architecture/guide/architecture-styles/'},{label:'Spring Data repositories',href:'https://docs.spring.io/spring-data/commons/reference/repositories.html'},{label:'Architecture Decision Records',href:'https://adr.github.io/'}]}
];
export const architecturePatternsPages=createTopicPages(specs);
