'use client';
import { createTopicPages, type TopicPageSpec } from './topic-page';

const specs: TopicPageSpec[] = [
  {id:'cache-aside',chapter:'Caching foundations',title:'Cache-aside step by step',answer:'The application checks the cache first. On a miss it reads the source of truth, stores a copy with an expiration, and returns it. Writes normally commit to the database and then invalidate the cached copy.',flow:['Read cache','Miss: read database','Store copy with TTL','Return value'],callout:{title:'Ordering matters',text:'Invalidating before a database commit can let another request repopulate the cache with the old value.'}},
  {id:'cache-location',chapter:'Caching foundations',title:'Local and distributed caches',answer:'A local cache avoids network latency but every instance owns a different copy. A distributed cache gives instances a shared cache and larger capacity but becomes a remote dependency.',comparisons:[{title:'Local cache',text:'Fastest; good for small, stable reference data. Harder invalidation and duplicated memory.'},{title:'Distributed cache',text:'Shared view and centralized eviction. Adds network, serialization, hot-key, and outage concerns.'}]},
  {id:'consistency',chapter:'Correctness',title:'Keeping cache and database consistent',answer:'Perfect atomic consistency between an ordinary cache and database is rarely available. Define acceptable staleness, update the source first, invalidate cached copies, and use versions or reconciliation for important data.',sections:[{title:'Race example',text:'A slow reader fetches version 1, a writer commits version 2 and invalidates, then the slow reader stores version 1. Version checks, short TTLs, or write-aware invalidation reduce this race.'}],callout:{title:'Source of truth',text:'If losing the cache loses business data, it is no longer merely a cache.'}},
  {id:'stampede',chapter:'Load protection',title:'Cache stampede and hot keys',answer:'When a popular key expires, many requests can miss together and overload the database. Prevent this with request coalescing, per-key locks, early refresh, TTL jitter, or stale-while-revalidate.',flow:['Hot key expires','Many requests miss','One request refreshes','Others wait or use stale data'],sections:[{title:'TTL jitter',text:'Randomized expiration spreads related keys across time, though it does not solve one extremely hot key.'}]},
  {id:'stale-negative',chapter:'Load protection',title:'Stale-while-revalidate and negative caching',answer:'Stale-while-revalidate serves a recently expired value while one worker refreshes it. Negative caching briefly stores “not found” to protect the source from repeated misses.',sections:[{title:'Safety limits',text:'Only serve stale data within a defined window and for tolerant domains. Negative entries need short TTLs so newly created data appears soon.'}]},
  {id:'cache-outage',chapter:'Reliability',title:'When the cache is unavailable',answer:'Choose whether to fail open to the database, fail closed, or serve stale data. Blindly sending all traffic to the database can turn a cache outage into a database outage.',sections:[{title:'Protect the source',bullets:['Use tight cache timeouts.','Limit fallback concurrency.','Shed optional traffic.','Warm gradually after recovery.','Monitor misses, latency, errors, evictions, and hot keys.']}]},
  {id:'eviction',chapter:'Capacity',title:'TTL and eviction policies',answer:'TTL removes data by age. Eviction removes data when capacity is full. LRU approximates least recently used; LFU favors frequently used values. Real systems use approximations to avoid expensive perfect global order.',sections:[{title:'Choose from access patterns',text:'No policy fixes a cache too small for its working set or keys with unbounded cardinality.'}]},
  {id:'key-design',chapter:'Data design',title:'Cache keys and invalidation boundaries',answer:'A key should encode namespace, stable identity, relevant query parameters, tenant, and representation version. It must distinguish every input that can change the result.',codeLabel:'Readable keys',code:'customer:v3:{tenantId}:{customerId}\nproducts:v2:{locale}:{category}:{page}\npermission:v4:{userId}:{resourceId}',sections:[{title:'Avoid',text:'Do not put secrets or raw personal data in keys. Avoid unstable serialization and designs requiring full-cache scans to invalidate.'}]},
  {id:'do-not-cache',chapter:'Judgment',title:'What should not be cached?',answer:'Avoid caching data whose staleness violates safety unless version validation exists. Avoid low-reuse data, unbounded personalized queries, secrets, and objects costlier to serialize than recompute.',callout:{title:'Cache only with a reason',text:'Measure hit rate, saved work, latency, and operational cost.'}},
  {id:'caching-recap',chapter:'Daily recap',title:'Caching interview checklist',answer:'Name the source of truth, read and write paths, staleness budget, stampede protection, capacity policy, and outage behavior.',sections:[{title:'A complete answer',bullets:['Why this data benefits from caching','Where the cache lives','How keys and TTLs are chosen','How writes invalidate copies','How hot keys and misses are controlled','What happens during failure']}],links:[{label:'Redis caching patterns',href:'https://redis.io/learn/howtos/solutions/microservices/caching'},{label:'Redis eviction policies',href:'https://redis.io/docs/latest/develop/reference/eviction/'}]}
];
export const cachingPages = createTopicPages(specs);
