'use client';
import { createTopicPages, type TopicPageSpec } from './topic-page';
const specs: TopicPageSpec[] = [
  {id:'images',chapter:'Containers',title:'Docker image layers and multi-stage builds',answer:'An image is an ordered set of immutable filesystem layers plus configuration. Docker reuses unchanged layers. A multi-stage build compiles in one image and copies only runtime artifacts into a smaller final image.',codeLabel:'Java multi-stage Dockerfile',code:'FROM eclipse-temurin:25-jdk AS build\nCOPY . /src\nWORKDIR /src\nRUN ./gradlew bootJar\n\nFROM eclipse-temurin:25-jre\nCOPY --from=build /src/build/libs/app.jar /app.jar\nUSER 10001\nENTRYPOINT ["java","-jar","/app.jar"]',sections:[{title:'Build safely',text:'Pin trusted base versions, keep build context small, run as non-root, scan dependencies and images, and never bake secrets into layers.'}]},
  {id:'java-containers',chapter:'Containers',title:'Java inside a container',answer:'Modern JVMs detect container CPU and memory limits, but the Java heap is only part of process memory. Metaspace, code cache, thread stacks, direct buffers, native libraries, and the JVM itself also count against the limit.',sections:[{title:'Why the container can die below -Xmx',text:'The kernel kills the process when total resident memory exceeds the cgroup limit. Leave native headroom, bound threads and direct memory, and monitor container working set with heap usage.'}]},
  {id:'k8s-objects',chapter:'Kubernetes',title:'Pods, Deployments, and Services',answer:'A Pod is the scheduling and networking unit containing one or more tightly coupled containers. A Deployment manages stateless Pod replicas and rollouts. A Service gives a stable virtual endpoint that selects Pods by labels.',flow:['Deployment declares replicas','Scheduler places Pods','Service selects ready Pods','Clients use stable address']},
  {id:'probes',chapter:'Kubernetes',title:'Startup, readiness, and liveness probes',answer:'Startup protects slow initialization. Readiness controls whether a Pod receives traffic. Liveness decides whether Kubernetes should restart a stuck container.',callout:{title:'Common mistake',text:'A liveness probe should not fail merely because an external database is briefly down; restarting every instance can amplify the outage.'}},
  {id:'rolling-shutdown',chapter:'Kubernetes',title:'Rolling deployment and graceful shutdown',answer:'A rolling update gradually adds new Pods and removes old ones while readiness gates traffic. During termination, the application should stop accepting new work, finish bounded in-flight work, and close resources before the grace period expires.',flow:['New Pod starts','Startup/readiness pass','Old Pod becomes unready','Old process drains and exits'],sections:[{title:'Spring Boot',text:'Enable graceful server shutdown, align application timeout with terminationGracePeriodSeconds, and handle SIGTERM. Long jobs need explicit ownership or checkpointing.'}]},
  {id:'resources-scaling',chapter:'Kubernetes',title:'Requests, limits, and autoscaling',answer:'A request is the resource amount used for scheduling and capacity planning. A limit constrains use. Horizontal autoscaling changes replica count from metrics; vertical scaling changes resource size.',sections:[{title:'CPU versus memory',text:'CPU limits throttle. Exceeding a memory limit can cause OOM kill. Autoscaling cannot rescue work instantly, so maintain headroom and choose metrics that track demand, such as queue lag or concurrency.'}]},
  {id:'configuration',chapter:'Kubernetes',title:'Configuration and secrets',answer:'ConfigMaps hold non-secret configuration. Secrets are a Kubernetes API object for sensitive bytes but require encryption at rest, RBAC, careful mounting, and ideally integration with a managed secret system.',sections:[{title:'Operational rule',text:'Version configuration, validate it at startup, separate it from images, and design credential rotation without logging values.'}]},
  {id:'migrations',chapter:'Delivery safety',title:'Safe database migrations',answer:'Use expand-and-contract: add backward-compatible schema, deploy code that can handle old and new forms, migrate data gradually, switch reads, then remove the old schema in a later release.',flow:['Expand schema','Deploy compatible code','Backfill and verify','Contract later'],callout:{title:'Avoid rollout coupling',text:'A rolling deployment temporarily runs old and new application versions together, so the schema must support both.'}},
  {id:'strategies',chapter:'Delivery safety',title:'Rolling, blue-green, canary, and rollback',answer:'Rolling replaces instances gradually. Blue-green keeps two complete environments and switches traffic. Canary exposes a small traffic share before expansion. Rollback restores application code, but irreversible data changes need forward fixes or compatible migrations.',comparisons:[{title:'Canary',text:'Limits blast radius and validates production signals; requires traffic control and automated analysis.'},{title:'Blue-green',text:'Fast switch and rollback at higher duplicate-environment cost.'}]},
  {id:'pipeline',chapter:'CI/CD',title:'A trustworthy CI/CD pipeline',answer:'A pipeline should produce one immutable artifact, verify it progressively, sign or attest it, deploy the same artifact through environments, and gate promotion on evidence.',flow:['Build + unit tests','Integration + security checks','Publish immutable artifact','Deploy and verify'],sections:[{title:'Feature flags',text:'Flags separate code deployment from feature exposure. Give each flag an owner and removal date; secure server-side evaluation for privileged behavior.'}]},
  {id:'iac-cloud',chapter:'Cloud foundations',title:'Infrastructure as code, IAM, and availability zones',answer:'Infrastructure as code makes desired infrastructure reviewable and repeatable. Terraform builds a dependency graph and compares configuration with state. IAM grants identities only necessary actions. Multiple availability zones reduce single-datacenter failure risk.',sections:[{title:'State and drift',text:'Protect remote Terraform state with locking and access control. Review plans, detect manual drift, and avoid placing secrets in state when possible.'}]},
  {id:'supply-chain',chapter:'Supply-chain security',title:'Dependency scanning, secret scanning, and SBOMs',answer:'Dependency scanning finds known vulnerable components. Secret scanning detects credentials. An SBOM inventories shipped components. Image scanning and provenance attestations add evidence about the artifact and its build.',sections:[{title:'Respond, do not merely scan',text:'Define severity policy, suppress only with documented reason and expiry, rebuild patched base layers, rotate exposed credentials, and track remediation time.'}]},
  {id:'commands',chapter:'Practical toolkit',title:'Essential Docker and Kubernetes commands',answer:'Use commands to observe desired state, actual state, events, logs, resources, and rollout history before changing anything.',codeLabel:'First-response commands',code:'docker build -t interview-prep:local .\ndocker history interview-prep:local\nkubectl get pods -n <ns> -o wide\nkubectl describe pod <pod> -n <ns>\nkubectl logs <pod> -n <ns> --previous\nkubectl top pod -n <ns>\nkubectl rollout status deployment/<name> -n <ns>\nkubectl rollout undo deployment/<name> -n <ns>',callout:{title:'Production caution',text:'Capture events, logs, image digest, and rollout revision before restart or rollback removes useful evidence.'}},
  {id:'cloud-recap',chapter:'Daily recap',title:'Container and delivery checklist',answer:'Build minimal immutable artifacts, budget total process memory, use correct probes, deploy backward-compatible changes, and make rollback and observability part of the release design.',sections:[{title:'Senior answer',bullets:['Explain the object or mechanism.','Describe the failure it prevents.','Name the operational signal.','Show the safe rollout and recovery path.']}],links:[{label:'Docker build guide',href:'https://docs.docker.com/build/'},{label:'Kubernetes concepts',href:'https://kubernetes.io/docs/concepts/'},{label:'Terraform documentation',href:'https://developer.hashicorp.com/terraform/docs'}]}
];
export const cloudDeploymentPages=createTopicPages(specs);
