'use client';
import { createTopicPages, type TopicPageSpec } from './topic-page';

const specs: TopicPageSpec[] = [
  {id:'partial-failure',chapter:'Failure model',title:'Partial failure changes everything',answer:'Across a network, the caller may time out without knowing whether the server never received the request, completed it, or completed it but lost the response.',flow:['Request leaves caller','Network or server fails','Caller sees timeout','Outcome may be unknown'],callout:{title:'Core nuance',text:'A timeout is an observation about waiting, not proof that the operation failed.'}},
  {id:'timeouts',chapter:'Failure model',title:'Timeouts and deadline budgets',answer:'Every remote call needs a finite timeout. A request-wide deadline should be divided across downstream calls so work stops before the client has already given up.',sections:[{title:'Choose from evidence',text:'Base connection and response timeouts on latency distributions and the caller deadline. Too short creates false failures; too long ties up threads, sockets, and pool entries.'},{title:'Propagate cancellation',text:'Pass deadlines downstream and cancel abandoned work when the protocol permits.'}]},
  {id:'retry-decisions',chapter:'Retries',title:'Which failures should be retried?',answer:'Retry transient failures that may succeed soon, such as a brief connection reset, selected 5xx responses, or rate limits with guidance. Do not retry validation, authorization, or deterministic business rejection.',comparisons:[{title:'Retryable',text:'Temporary unavailability, throttling, leader election, or a connection failure before sending.'},{title:'Not retryable',text:'Malformed input, forbidden access, missing required data, or an invariant violation.'}],callout:{title:'Budget retries',text:'Cap attempts and total elapsed time because every retry adds load and latency.'}},
  {id:'backoff-jitter',chapter:'Retries',title:'Exponential backoff and jitter',answer:'Exponential backoff increases the delay after each failure. Jitter randomizes that delay so thousands of clients do not retry in synchronized waves.',codeLabel:'Illustrative Java',code:'long cap = 2_000;\nlong exponential = 100L << attempt;\nlong delay = ThreadLocalRandom.current()\n    .nextLong(Math.min(cap, exponential) + 1);',sections:[{title:'Why both matter',text:'Backoff lowers pressure; jitter spreads retries across time. Honor Retry-After when the server supplies it.'}]},
  {id:'idempotent-retries',chapter:'Retries',title:'Retries require idempotency',answer:'A retry can repeat an operation whose response was lost. Use an idempotency key, unique business constraint, or deduplication record so repeated execution produces one business effect.',flow:['Client creates stable key','Server checks stored outcome','First request commits result','Retry returns same result'],callout:{title:'Example',text:'Store a payment result under the client operation ID in the same durable boundary as the payment record.'}},
  {id:'circuit-bulkhead',chapter:'Failure isolation',title:'Circuit breakers and bulkheads',answer:'A circuit breaker fails fast after a dependency crosses a failure threshold and later probes recovery. A bulkhead limits concurrency or resources so one failing dependency cannot consume the whole service.',comparisons:[{title:'Circuit breaker',text:'Controls whether calls are attempted from recent outcomes.'},{title:'Bulkhead',text:'Controls how many resources a call path may occupy.'}]},
  {id:'rate-load',chapter:'Failure isolation',title:'Rate limiting and load shedding',answer:'Rate limiting enforces an allowed request rate, often per client. Load shedding rejects lower-priority work when current capacity is exhausted, protecting work already in progress.',sections:[{title:'Make overload explicit',text:'Return 429 or 503 with retry guidance where appropriate. Silent queue growth converts overload into timeouts and memory pressure.'}]},
  {id:'eventual-workflows',chapter:'Consistency',title:'Sagas, outbox, and reconciliation',answer:'A saga coordinates local transactions with later steps and compensations. The transactional outbox commits a state change and event record together. Reconciliation compares intended and actual state to repair gaps.',flow:['Local transaction + outbox','Publisher sends event','Next service commits','Reconciler repairs exceptions'],sections:[{title:'Why avoid distributed transactions',text:'Two-phase coordination expands the failure boundary. Local transactions plus explicit recovery are usually more operable.'}]},
  {id:'cascades',chapter:'Failure isolation',title:'Preventing cascading failures',answer:'Cascades happen when one slow dependency makes callers wait, exhausts resources, triggers retries, and spreads saturation upstream.',flow:['Dependency slows','Caller pools fill','Retries add load','More services fail'],sections:[{title:'Break the chain',bullets:['Bound queues and timeouts.','Use concurrency limits and bulkheads.','Apply retry budgets with jitter.','Degrade gracefully and shed load.']}]},
  {id:'tracing',chapter:'Observability',title:'Distributed tracing and correlation IDs',answer:'A trace represents one request across services; spans represent operations. Trace context propagates in standard headers. A correlation ID is a searchable business or request identifier and may coexist with the trace ID.',sections:[{title:'What each signal answers',text:'Traces expose a request path. Metrics show aggregate health. Logs preserve detailed events. One cannot replace the others.'}]},
  {id:'delivery-anomalies',chapter:'Messaging failures',title:'Duplicates and out-of-order events',answer:'At-least-once delivery creates duplicates. Partitioning and retries can expose events out of business order.',sections:[{title:'Handle duplicates',text:'Use a stable event ID and record consumption atomically with the side effect, or make the side effect naturally idempotent.'},{title:'Handle order',text:'Partition by entity, include an entity version, reject stale updates, and reconcile gaps.'}]},
  {id:'resilience-recap',chapter:'Daily recap',title:'Resilience answer framework',answer:'State the ambiguous outcome, bound resource use, retry only safe operations, isolate failures, and design durable recovery.',sections:[{title:'Five questions',bullets:['What is the deadline?','Is the operation idempotent?','Which failures are transient?','How is concurrency bounded?','How are missing, duplicated, or delayed effects reconciled?']}],links:[{label:'AWS timeouts and retries',href:'https://aws.amazon.com/builders-library/timeouts-retries-and-backoff-with-jitter/'},{label:'OpenTelemetry concepts',href:'https://opentelemetry.io/docs/concepts/'}]}
];
export const distributedSystemsPages = createTopicPages(specs);
