'use client';
import { createTopicPages, type TopicPageSpec } from './topic-page';
const specs: TopicPageSpec[] = [
  {id:'models',chapter:'Messaging foundations',title:'Queues, publish-subscribe, commands, and events',answer:'A queue distributes work among consumers. Publish-subscribe delivers a message to multiple subscriptions. A command asks one owner to act; an event records a fact that already happened.',comparisons:[{title:'Command',text:'Imperative intent: ReserveInventory. Usually one logical handler may accept or reject it.'},{title:'Event',text:'Past-tense fact: InventoryReserved. Any interested consumer may react, and the publisher does not direct their behavior.'}]},
  {id:'delivery',chapter:'Delivery semantics',title:'At-most-once and at-least-once delivery',answer:'At-most-once may lose a message but does not redeliver it. At-least-once retries until acknowledged, so duplicates are expected. “Exactly once” is always scoped to specific broker and transaction boundaries.',flow:['Broker delivers','Consumer performs side effect','Acknowledgement is lost','Broker redelivers'],callout:{title:'Critical case',text:'If processing succeeds but acknowledgement fails, the same message returns. The consumer must be idempotent.'}},
  {id:'idempotent-consumer',chapter:'Delivery semantics',title:'Building an idempotent consumer',answer:'Give every message a stable ID. In the same database transaction as the business effect, insert that ID into a table with a unique constraint. If insertion conflicts, the message was already processed.',codeLabel:'Transactional outline',code:'BEGIN;\nINSERT INTO consumed_message(id) VALUES (?) ON CONFLICT DO NOTHING;\n-- only apply business change when the insert succeeded\nCOMMIT;',sections:[{title:'Natural idempotency',text:'Setting status to SHIPPED can be idempotent; incrementing a balance is not unless tied to a unique operation.'}]},
  {id:'ordering',chapter:'Ordering and scale',title:'Ordering, partitions, and consumer groups',answer:'Global order limits parallelism. Brokers commonly guarantee order only within a partition or queue. Put messages for the same business entity on the same partition when per-entity order matters.',sections:[{title:'Consumer groups',text:'Consumers in one group compete for partitions or messages, sharing work. Separate groups each receive their own logical copy.'},{title:'Defend against stale events',text:'Include an entity version or sequence. Apply the next version, ignore older versions, and reconcile gaps rather than trusting arrival time.'}]},
  {id:'retry-dlq',chapter:'Failure handling',title:'Retries, dead-letter queues, and poison messages',answer:'Retry transient failures with capped backoff. A message that repeatedly fails moves to a dead-letter queue for diagnosis and controlled replay. A poison message fails deterministically because its data or schema is unusable.',flow:['Consume','Classify failure','Retry transient error','DLQ persistent error'],callout:{title:'A DLQ is not resolution',text:'Alert on it, preserve failure context, provide replay tooling, and fix the consumer or data before replay.'}},
  {id:'lag-backpressure',chapter:'Capacity',title:'Queue depth, consumer lag, and backpressure',answer:'Queue depth is waiting message count. Consumer lag measures how far processing trails production, often by offsets. Growth means arrival rate exceeds effective processing rate or consumers are failing.',sections:[{title:'Respond safely',bullets:['Scale consumers within partition limits.','Reduce producer rate or shed optional work.','Bound per-consumer concurrency.','Measure oldest-message age, not only count.','Fix slow dependencies before adding workers.']}]},
  {id:'schema',chapter:'Contracts',title:'Schema evolution',answer:'Events are durable contracts because old messages and independently deployed consumers coexist. Prefer additive changes, tolerant readers, explicit versions, compatibility checks, and deprecation periods.',sections:[{title:'Breaking changes',text:'Renaming or changing meaning is breaking even if the wire type remains valid. Publish a new field or event version and migrate consumers deliberately.'}]},
  {id:'outbox-inbox',chapter:'Consistency',title:'Transactional outbox and inbox',answer:'The outbox stores a domain change and pending event in one local transaction, then a publisher sends it. An inbox or consumed-message table deduplicates deliveries at the consumer.',flow:['Commit state + outbox','Publish asynchronously','Consume message','Commit effect + inbox'],callout:{title:'What it guarantees',text:'The outbox closes the database-versus-publish gap; it still produces duplicates, so consumers remain idempotent.'}},
  {id:'messaging-choice',chapter:'Technology choice',title:'Messaging versus synchronous REST',answer:'Choose REST or gRPC for an immediate answer. Choose messaging for asynchronous work, buffering, fan-out, and availability decoupling when eventual completion is acceptable.',comparisons:[{title:'Kafka',text:'Partitioned durable log, replay, high throughput, and consumer-controlled offsets; strong for event streams.'},{title:'RabbitMQ',text:'Flexible exchanges, routing, acknowledgements, and work queues; strong for broker-mediated delivery.'},{title:'Cloud queues',text:'Managed durability and scaling with provider-specific ordering, visibility, size, and retention rules.'}]},
  {id:'messaging-recap',chapter:'Daily recap',title:'Messaging design checklist',answer:'Define message meaning, delivery semantics, ordering scope, idempotency, failure routing, schema evolution, and capacity signals before selecting a broker.',sections:[{title:'Interview questions to answer',bullets:['Who owns the command or event?','What happens after success but before acknowledgement?','Which key requires ordering?','How are duplicates recorded?','When does retry stop?','How are lag and DLQs operated?']}],links:[{label:'Apache Kafka documentation',href:'https://kafka.apache.org/documentation/'},{label:'RabbitMQ documentation',href:'https://www.rabbitmq.com/docs'},{label:'Amazon SQS developer guide',href:'https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/welcome.html'}]}
];
export const messagingEventDrivenPages=createTopicPages(specs);
