'use client';
import { createTopicPages, type TopicPageSpec } from './topic-page';
const specs: TopicPageSpec[] = [
  {id:'request-chain',chapter:'Networking foundations',title:'From URL to HTTP response',answer:'The client resolves a hostname with DNS, opens a TCP connection, negotiates TLS for HTTPS, sends an HTTP request, and receives response headers and a body. Connection reuse avoids repeating much of this work.',flow:['DNS lookup','TCP connection','TLS handshake','HTTP exchange'],sections:[{title:'Where latency appears',text:'DNS misses, connection establishment, TLS, proxy queues, application work, downstream calls, and response transfer each contribute.'}]},
  {id:'http-versions',chapter:'Networking foundations',title:'HTTP/1.1 and HTTP/2',answer:'HTTP/1.1 commonly uses several reusable connections to gain concurrency. HTTP/2 multiplexes many streams over one connection and compresses headers, reducing connection count and application-level head-of-line blocking.',sections:[{title:'Important limit',text:'HTTP/2 still runs over TCP, so packet loss can delay streams sharing that connection. HTTP/3 changes the transport to QUIC.'}]},
  {id:'pooling',chapter:'Networking foundations',title:'Connection pooling, keep-alive, and socket exhaustion',answer:'A connection pool reuses established sockets and bounds concurrent calls. If responses are not closed, timeouts are unbounded, or concurrency exceeds limits, the pool or operating-system ports can be exhausted.',sections:[{title:'Diagnose',text:'Measure leased, idle, pending, acquisition time, connection age, and timeout counts. Compare with server limits and TIME_WAIT or established socket counts.'}],codeLabel:'Useful network checks',code:'curl -v https://service.example/health\nnslookup service.example\nTest-NetConnection service.example -Port 443'},
  {id:'proxy-balancer',chapter:'Network infrastructure',title:'Reverse proxies and load balancers',answer:'A reverse proxy accepts client traffic and forwards it to servers, often adding TLS, routing, and policy. A load balancer focuses on distributing traffic across healthy targets; one product may perform both roles.',comparisons:[{title:'Layer 4',text:'Routes TCP or UDP using addresses and ports; low overhead and little application awareness.'},{title:'Layer 7',text:'Understands HTTP host, path, headers, cookies, and status; enables content routing and richer policy.'}]},
  {id:'auth',chapter:'Identity and access',title:'Authentication, authorization, OAuth 2.0, OIDC, and JWT',answer:'Authentication establishes who or what is calling. Authorization decides what that principal may do. OAuth 2.0 delegates API access; OpenID Connect adds identity authentication. JWT is a token format, not an authorization strategy.',sections:[{title:'Validate a JWT',bullets:['Verify signature using trusted keys and an allowed algorithm.','Validate issuer, audience, expiry, and not-before.','Apply authorization from trusted claims and current policy.','Plan key rotation and token revocation or short lifetimes.']}]},
  {id:'sessions',chapter:'Identity and access',title:'Sessions and tokens',answer:'A session cookie carries an opaque identifier and the server stores session state. A self-contained access token carries signed claims and reduces central lookup, but remains valid until expiry unless extra revocation is added.',callout:{title:'Browser safety',text:'Protect cookies with Secure, HttpOnly, SameSite, and CSRF controls. Do not store long-lived sensitive tokens where injected JavaScript can read them.'}},
  {id:'cors-csrf',chapter:'Browser security',title:'CORS and CSRF solve different problems',answer:'CORS controls whether browser JavaScript may read cross-origin responses. CSRF protection prevents another site from causing a browser to submit an authenticated unwanted request.',comparisons:[{title:'CORS',text:'A browser-enforced response-access policy; it is not authentication.'},{title:'CSRF',text:'Relevant when credentials are sent automatically, especially cookies. Use SameSite plus anti-CSRF tokens or origin checks.'}]},
  {id:'web-threats',chapter:'Application security',title:'SQL injection, XSS, and SSRF',answer:'SQL injection turns input into query syntax; use parameters. XSS executes attacker-controlled content in a browser; encode for the output context and use CSP. SSRF makes the server call attacker-chosen destinations; allowlist and restrict network egress.',sections:[{title:'Do not rely on filtering alone',text:'Use APIs that separate data from code, contextual output encoding, strict URL parsing, DNS/IP validation, redirect limits, and least-privilege networks.'}]},
  {id:'service-security',chapter:'Service security',title:'Securing service-to-service communication',answer:'Authenticate workloads, encrypt traffic, authorize each service identity, and issue short-lived credentials. Mutual TLS can establish both client and server identity, while OAuth access tokens carry scoped authorization.',sections:[{title:'Defense in depth',bullets:['Default-deny network policy','Least-privilege service accounts','Certificate and key rotation','Audience-restricted tokens','Authorization at the receiving service']}]},
  {id:'secrets',chapter:'Secrets',title:'Secret storage and rotation',answer:'Keep secrets in a managed secret store, grant access to workload identities, load them at runtime, audit reads, and rotate without redeploying every consumer when possible.',sections:[{title:'Never expose',text:'Do not place secrets in source code, images, URLs, metrics labels, traces, logs, exception responses, or client-side bundles. Redact sensitive headers and fields centrally.'}]},
  {id:'security-recap',chapter:'Daily recap',title:'Networking and security checklist',answer:'Trace the request layer by layer, bound and reuse connections, establish identity, authorize least privilege, and prevent untrusted input from becoming code or unrestricted network access.',sections:[{title:'Interview sequence',bullets:['DNS, transport, TLS, HTTP','Proxy routing and connection pools','Authentication then authorization','Browser threat model','Input and output boundaries','Workload identity and secret lifecycle']}],links:[{label:'MDN HTTP overview',href:'https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview'},{label:'OAuth 2.0 security best practices',href:'https://www.rfc-editor.org/rfc/rfc9700'},{label:'OWASP Cheat Sheet Series',href:'https://cheatsheetseries.owasp.org/'}]}
];
export const networkingSecurityPages=createTopicPages(specs);
