'use client';
import { createTopicPages, type TopicPageSpec } from './topic-page';
const specs: TopicPageSpec[] = [
  {id:'signals',chapter:'Observability foundations',title:'Logs, metrics, and traces',answer:'Metrics show aggregate behavior over time, logs explain discrete events, and traces show the path of individual requests. Correlation and trace IDs connect these views across services.',comparisons:[{title:'Metrics',text:'Cheap aggregation for alerting, rates, percentiles, saturation, and trends.'},{title:'Logs',text:'Structured event details for investigation; control volume and sensitive data.'},{title:'Traces',text:'Causal request path, spans, retries, errors, and downstream latency.'}]},
  {id:'percentiles',chapter:'Latency',title:'p50, p95, and p99 latency',answer:'p50 is the median: half of requests are faster. p95 and p99 expose the slow tail hidden by averages. A p99 of 900 ms means 1% of measured requests took longer than 900 ms.',sections:[{title:'Normal CPU, high tail latency',text:'Look for blocked threads, lock contention, GC pauses, connection-pool waits, storage latency, DNS/TLS delays, downstream calls, and retry amplification.'}]},
  {id:'triage',chapter:'Incident diagnosis',title:'A disciplined production triage loop',answer:'Confirm impact, narrow the failing path, compare the change timeline, inspect saturation and dependencies, then test one hypothesis at a time.',flow:['Scope symptoms','Correlate metrics and changes','Inspect traces and dumps','Mitigate then prove cause'],sections:[{title:'Separate major causes',bullets:['GC: pause time, allocation rate, heap after collection.','Locks: BLOCKED threads and common monitor owners.','I/O: waiting threads, slow spans, socket or disk latency.','Downstream: dependency error and latency metrics.']}]},
  {id:'npe-500',chapter:'Incident diagnosis',title:'Intermittent NullPointerException and HTTP 500 spikes',answer:'Group errors by exception fingerprint, endpoint, release, instance, and input shape. Follow a representative trace and structured log to the first application frame rather than counting only the top-level 500.',sections:[{title:'Intermittent NPE',text:'Capture the null-producing branch and request context safely. Look for optional upstream fields, races, partially initialized objects, cache misses, and mapping assumptions.'},{title:'500 spike',text:'Compare deployment, traffic, dependency, pool, and resource timelines. Roll back or disable a feature when evidence links a recent change and impact is ongoing.'}]},
  {id:'pools',chapter:'Saturation',title:'Thread pools and database connection pools',answer:'A pool is saturated when demand occupies all resources and callers wait. More pool entries can move overload to the database or downstream service rather than solve it.',sections:[{title:'Database pool metrics',bullets:['Active, idle, maximum, and pending waiters','Acquisition time and timeout count','Connection age and leak warnings','Transaction duration and slow queries']},{title:'Thread exhaustion',text:'Inspect active count, queue depth, completed-task rate, rejection count, and thread dumps. Find what workers are waiting on.'}]},
  {id:'leaks',chapter:'Saturation',title:'Connection leaks and long transactions',answer:'A connection leak never returns a borrowed connection. A long transaction returns it eventually but holds locks and pool capacity too long. Both increase acquisition waits until requests time out.',codeLabel:'Useful process commands',code:'jcmd <pid> Thread.print -l\njcmd <pid> JFR.start name=incident settings=profile duration=5m filename=incident.jfr\njcmd <pid> GC.heap_info',callout:{title:'Interpret before changing',text:'A dump is a snapshot. Compare several samples to distinguish a stuck owner from normal transient waiting.'}},
  {id:'metrics',chapter:'What to measure',title:'JVM, database, and downstream metrics',answer:'Measure traffic, errors, latency, and saturation at each boundary. Add JVM allocation, heap-after-GC, pause time, thread states, and CPU; database query and pool signals; downstream latency, errors, timeouts, and circuit state.',sections:[{title:'Avoid cardinality explosions',text:'Do not put raw user IDs, URLs, exception messages, or request IDs in metric labels. Keep those details in sampled traces or structured logs.'}]},
  {id:'mitigation',chapter:'Incident response',title:'Immediate mitigation and post-incident work',answer:'First reduce user impact with rollback, traffic reduction, feature disablement, capacity, or dependency isolation. Preserve evidence. Then identify contributing conditions and durable safeguards.',sections:[{title:'Post-incident actions',bullets:['Build a factual timeline.','Explain why defenses did not contain impact.','Assign concrete owners and dates.','Add a regression test or operational guard.','Update dashboards, alerts, and runbooks.']}]},
  {id:'slo',chapter:'Reliability management',title:'SLIs, SLOs, and error budgets',answer:'An SLI is a measured service property such as successful-request ratio or latency. An SLO is its target over a window. The error budget is the allowed unreliability: 100% minus the target.',sections:[{title:'Why budgets matter',text:'A 99.9% availability target allows 0.1% unsuccessful requests in the window. Burn-rate alerts detect whether that allowance is being consumed too quickly and inform release versus reliability work.'}]},
  {id:'toolkit',chapter:'Practical toolkit',title:'Install and use an observability toolkit',answer:'Start with application metrics and OpenTelemetry instrumentation, centralized structured logs, and trace export. Keep JDK command-line tools available in the same Java version as production.',codeLabel:'First-response commands',code:'curl -s http://host/actuator/health\ncurl -s http://host/actuator/prometheus\njcmd <pid> VM.flags\njcmd <pid> Thread.print -l\njstat -gcutil <pid> 1000\n# container\nkubectl top pod -n <namespace>\nkubectl logs -n <namespace> <pod> --since=15m',sections:[{title:'OpenTelemetry path',text:'Instrument the service with the Java agent or SDK, export OTLP to a collector, then route traces and metrics to your backend. Verify trace-context propagation at every boundary.'}]},
  {id:'observability-recap',chapter:'Daily recap',title:'Production investigation checklist',answer:'Measure impact, correlate signals, inspect the constrained resource, mitigate safely, preserve evidence, and verify the recovery with the same user-facing SLI.',sections:[{title:'Interview structure',bullets:['State the symptom and affected SLI.','Name the metrics that separate hypotheses.','Use traces and dumps to find the wait or hot path.','Describe immediate containment.','Explain the durable prevention and validation.']}],links:[{label:'OpenTelemetry Java',href:'https://opentelemetry.io/docs/languages/java/'},{label:'Prometheus documentation',href:'https://prometheus.io/docs/introduction/overview/'},{label:'JDK jcmd guide',href:'https://docs.oracle.com/en/java/javase/25/docs/specs/man/jcmd.html'}]}
];
export const productionObservabilityPages=createTopicPages(specs);
