'use client';
import { createTopicPages, type TopicPageSpec } from './topic-page';

const specs: TopicPageSpec[] = [
  {id:'observable-service',chapter:'Foundations',title:'What an observable Java service should expose',answer:'A production service should reveal demand, failures, latency, and saturation at every important boundary. Metrics show whether a problem is widespread, traces show where request time went, logs explain specific events, and profiles or dumps explain what the JVM was doing.',sections:[
    {title:'Start with four signals',bullets:['Traffic: requests or jobs per second. A sudden drop can mean lost traffic, rejection, or upstream failure.','Errors: failed requests, exceptions, timeouts, and rejected work. Separate client errors from server failures.','Latency: p50 shows typical experience; p95 and p99 expose the slow tail.','Saturation: pool usage, queues, CPU throttling, heap pressure, or connection waiters show a resource approaching its limit.']},
    {title:'Example',text:'Checkout p99 rises from 300 ms to 4 s while CPU stays at 25%. That combination suggests waiting rather than expensive computation. Check request traces, database-pool waiters, executor queues, locks, and downstream latency before changing CPU limits.'}
  ],callout:{title:'Do not start by searching every log',text:'Use a user-facing metric to define the affected time, route, region, version, and instance. Then inspect traces and logs from that narrowed population.'}},
  {id:'install-metrics',chapter:'Instrumentation',title:'Install Spring Boot metrics and Prometheus export',answer:'Spring Boot Actuator uses Micrometer to record JVM, process, HTTP, connection-pool, and application metrics. The Prometheus registry converts those measurements into a scrape endpoint that Prometheus reads periodically.',codeLabel:'Dependencies and safe endpoint exposure',code:'<dependency>\n  <groupId>org.springframework.boot</groupId>\n  <artifactId>spring-boot-starter-actuator</artifactId>\n</dependency>\n<dependency>\n  <groupId>io.micrometer</groupId>\n  <artifactId>micrometer-registry-prometheus</artifactId>\n</dependency>\n\nmanagement.endpoints.web.exposure.include=health,info,metrics,prometheus\nmanagement.endpoint.health.probes.enabled=true',sections:[
    {title:'Verify locally',bullets:['GET /actuator/health confirms application health endpoints respond.','GET /actuator/metrics lists Micrometer meter names such as http.server.requests.','GET /actuator/metrics/http.server.requests shows measurements and available tags.','GET /actuator/prometheus returns Prometheus names such as http_server_requests_seconds_count.']},
    {title:'What the names mean',text:'A counter ending in _count only increases until restart. A gauge can rise and fall, such as active connections. A histogram exposes _bucket counts so the monitoring system can estimate percentiles across many instances.'}
  ],callout:{title:'Secure diagnostics',text:'Keep Actuator behind authentication and a private network. Heap dumps, environment, configuration, and log-level endpoints can expose secrets or alter runtime behavior.',tone:'warning'}},
  {id:'install-tracing',chapter:'Instrumentation',title:'Add distributed tracing and correlated logs',answer:'The OpenTelemetry Java agent instruments common HTTP, database, and messaging libraries without application code changes. It creates spans, propagates trace context, and can correlate trace and span IDs with logs.',codeLabel:'Start with the OpenTelemetry Java agent',code:'java -javaagent:/opt/otel/opentelemetry-javaagent.jar \\\n  -Dotel.service.name=order-service \\\n  -Dotel.exporter.otlp.endpoint=http://otel-collector:4318 \\\n  -Dotel.exporter.otlp.protocol=http/protobuf \\\n  -jar app.jar\n\nOTEL_SERVICE_NAME=order-service\nOTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318',sections:[
    {title:'What a trace shows',text:'A 2.4-second request might contain 20 ms in the controller, 1.8 s waiting for PostgreSQL, and 550 ms in a payment call. That tells you where elapsed time accumulated; it does not prove why PostgreSQL was slow.'},
    {title:'Useful structured-log fields',bullets:['timestamp, severity, service, environment, version, and instance','trace_id and span_id for navigation from trace to logs','route template and status, never an unbounded raw URL','exception type and stable error code','business operation ID when safe; never passwords, tokens, or full personal records']}
  ],callout:{title:'Sampling nuance',text:'A trace backend may retain only part of traffic. Keep aggregate metrics for all requests and use tail or error-aware sampling when rare slow and failed traces matter.'}},
  {id:'first-ten-minutes',chapter:'Incident workflow',title:'Worked example: the first ten minutes of an incident',answer:'Suppose an alert says checkout success fell from 99.95% to 96%. First confirm customer impact and scope. Then correlate deployment, traffic, errors, latency, saturation, and dependencies before changing the system.',flow:['Confirm the SLI','Narrow dimensions','Compare dependencies','Mitigate and verify'],sections:[
    {title:'Minute 0–3: establish scope',bullets:['Is the alert still firing? Check success rate and request volume.','Is one route, region, tenant, version, or pod responsible?','Did traffic shape or a deployment change at the same time?']},
    {title:'Minute 3–7: separate hypotheses',bullets:['High CPU suggests execution pressure; low CPU with high latency suggests waiting.','Database pending connections suggest pool or database delay.','One slow child span suggests a dependency; many slow local spans suggest the service.','GC pause alignment suggests JVM pauses; stable GC signals make that less likely.']},
    {title:'Minute 7–10: contain impact',text:'Rollback a correlated release, disable the failing optional feature, reduce concurrency, shed low-priority work, or route away from a bad zone. Confirm recovery using the original checkout success metric.'}
  ]},
  {id:'latency-percentiles',chapter:'HTTP diagnostics',title:'Read p50, p95, and p99 correctly',answer:'p50 is the median. p95 means 95% of observations were at or below that value, while the slowest 5% were above it. p99 reveals a smaller and often important tail. Interpret percentiles with traffic volume and a time window.',codeLabel:'PromQL for Spring HTTP metrics',code:'# Requests per second\nsum(rate(http_server_requests_seconds_count[5m]))\n\n# Server-error ratio\nsum(rate(http_server_requests_seconds_count{status=~"5.."}[5m]))\n/ sum(rate(http_server_requests_seconds_count[5m]))\n\n# p99 from histogram buckets\nhistogram_quantile(0.99,\n  sum by (le) (rate(http_server_requests_seconds_bucket[5m]))\n)',sections:[
    {title:'How to interpret the graph',bullets:['p50 stable and p99 rising: a subset of requests, keys, instances, or dependencies is slow.','All percentiles rise: broad capacity pressure or a dependency used by most requests.','p99 spikes with low request count: inspect sample size; one request can dominate a tiny window.','Latency rises after retries increase: retry policy may be amplifying a dependency failure.']},
    {title:'Do not average percentiles',text:'Compute a fleet percentile from merged histogram buckets. Averaging per-instance p99 values is not the percentile of all requests.'}
  ]},
  {id:'latency-normal-cpu',chapter:'HTTP diagnostics',title:'High latency with normal CPU',answer:'Normal CPU often means requests are parked or blocked: waiting for a database connection, remote response, lock, executor slot, disk, DNS, or TLS. It can also hide one saturated core or short spikes averaged over a long interval.',codeLabel:'Capture waiting evidence',code:'jcmd <pid> Thread.print -l > threads-01.txt\njcmd <pid> Thread.print -l > threads-02.txt\njcmd <pid> JFR.start name=latency settings=profile duration=2m filename=latency.jfr\n\nkubectl top pod -n <namespace>\nkubectl describe pod <pod> -n <namespace>',sections:[
    {title:'What to look for',bullets:['Many threads on HikariPool.getConnection: database connections are unavailable or held too long.','Many threads in Socket.read: a downstream call is slow or missing a timeout.','Many BLOCKED threads on the same monitor: lock contention.','Executor queue rising while active threads equal maximum: work arrives faster than workers complete it.','JFR Thread Park, Java Monitor Blocked, Socket Read, and File Read events identify where elapsed time accumulated.']},
    {title:'Likely causes',text:'Slow SQL, long transactions, undersized or leaked pools, downstream saturation, retry storms, synchronized hot paths, DNS problems, storage latency, or queueing before execution.'}
  ]},
  {id:'http-500',chapter:'HTTP diagnostics',title:'HTTP 500 spike: metric to failing code path',answer:'First determine whether failures affect one route, release, instance, or dependency. Then select a failed trace and follow it to the first span or log containing the real exception rather than the final generic 500 response.',codeLabel:'PromQL and log commands',code:'# Errors grouped by route and status\nsum by (uri, status) (\n  rate(http_server_requests_seconds_count{status=~"5.."}[5m])\n)\n\nkubectl logs -n shop deployment/order-service --since=15m --prefix\nkubectl logs -n shop <pod> --previous',sections:[
    {title:'Example interpretation',text:'Only POST /orders returns 500, all failures run version 2026.09.28, and traces fail in TaxClient after a deployment. This points toward a release or tax integration change, not general JVM capacity.'},
    {title:'Common reasons',bullets:['Uncaught application exception or invalid assumption','Schema or configuration mismatch after deployment','Dependency timeout converted to 500','Pool timeout or rejected executor task','Serialization failure on a new response field','Pod restarts from OOM kill or failed liveness checks']}
  ],callout:{title:'Metric-tag nuance',text:'Spring can handle an exception and still omit the exception tag unless the handled exception is recorded as a request attribute. Validate what your framework version emits.'}},
  {id:'intermittent-npe',chapter:'HTTP diagnostics',title:'Intermittent NullPointerException: a concrete investigation',answer:'An intermittent NPE usually depends on a particular input, stale or missing data, partial upstream response, race, or code path. Group occurrences by stack fingerprint and compare the surrounding structured fields.',codeLabel:'Log enough context without leaking data',code:'log.error("order_mapping_failed orderId={} source={} version={}",\n    orderId, sourceSystem, payloadVersion, exception);',sections:[
    {title:'Example',text:'The same stack points to customer.address().country(). Failures occur only for guest checkout records imported by version 1 of an event. Query the event version and record shape, reproduce with a sanitized example, then make absence explicit or validate at the boundary.'},
    {title:'Evidence that changes the diagnosis',bullets:['Different stacks: several unrelated bugs; group them separately.','Same object is sometimes null under concurrent access: inspect unsafe publication or shared mutation.','Only cache misses fail: the database fallback or mapper differs from the cache path.','Only one pod fails: compare configuration, local cache, traffic, and application version.']}
  ]},
  {id:'executor-saturation',chapter:'Pool saturation',title:'Thread-pool exhaustion',answer:'A bounded executor is saturated when active threads stay at the maximum and the queue grows or rejects tasks. Work arrives faster than workers finish it; enlarging the queue only increases waiting and memory use.',codeLabel:'Representative executor metrics',code:'executor_active_threads\nexecutor_pool_max_threads\nexecutor_queued_tasks\nexecutor_completed_tasks_total\n\njcmd <pid> Thread.print -l',sections:[
    {title:'Metric patterns',bullets:['active ≈ max and queue rising: sustained saturation.','active low and queue high: workers may be unavailable, misconfigured, or the metrics refer to different executors.','rejections rising: queue and workers are full; callers need controlled overload behavior.','completed rate falls while active stays high: each task became slower, often because of a dependency.']},
    {title:'Find the real bottleneck',text:'If dumps show every worker waiting on the same HTTP call, that dependency, its timeout, or excessive concurrency is the bottleneck. Adding threads can create more pressure and worsen the outage.'}
  ]},
  {id:'database-pool',chapter:'Pool saturation',title:'HikariCP saturation and connection leaks',answer:'HikariCP active is borrowed connections, idle is immediately available capacity, max is the pool limit, and pending is application threads waiting to borrow. Persistent pending above zero means requests cannot obtain connections promptly.',codeLabel:'Actuator and Prometheus',code:'curl -s localhost:8080/actuator/metrics/hikaricp.connections.active\ncurl -s localhost:8080/actuator/metrics/hikaricp.connections.pending\n\nhikaricp_connections_active\nhikaricp_connections_idle\nhikaricp_connections_max\nhikaricp_connections_pending',sections:[
    {title:'Interpret combinations',bullets:['active = max and pending > 0: the pool is saturated.','active remains high after traffic falls: connections may be leaked or transactions are stuck.','pending rises while database CPU and query time rise: database work is the likely cause.','pending rises with normal database load: inspect pool size, connectivity, and which code holds connections.']},
    {title:'Leak versus long transaction',text:'A leak never closes the connection. A long transaction eventually returns it but holds the connection and possibly locks too long. Hikari leak detection reports the borrow stack; use a threshold longer than legitimate transactions and verify that the connection truly failed to return.'}
  ],callout:{title:'Do not increase the pool blindly',text:'The database has finite workers, memory, locks, and I/O. A larger application pool can raise contention and make every query slower.'}},
  {id:'slow-database',chapter:'Database diagnosis',title:'Slow query or database contention?',answer:'Trace spans show which SQL operation consumed time. Database statistics then separate expensive plans, lock waits, connection pressure, and storage or CPU saturation.',codeLabel:'PostgreSQL examples',code:'-- Current sessions and wait reasons\nSELECT pid, state, wait_event_type, wait_event,\n       now() - query_start AS age, query\nFROM pg_stat_activity\nWHERE state <> \'idle\'\nORDER BY age DESC;\n\nEXPLAIN (ANALYZE, BUFFERS)\nSELECT ...;',sections:[
    {title:'What the evidence means',bullets:['Long active query with CPU or I/O work: inspect plan, rows, indexes, and data distribution.','wait_event_type = Lock: find the blocker and transaction; query tuning alone will not remove the wait.','Many idle in transaction sessions: application transactions remain open and may hold locks.','Fast SQL spans but long connection-acquire spans: pool availability dominates latency.']},
    {title:'Useful tools',text:'Use pg_stat_activity for current sessions, pg_stat_statements for aggregated query time and calls, EXPLAIN for the chosen plan, and native lock views for blocker chains. Align database and trace timestamps.'}
  ]},
  {id:'gc-memory',chapter:'JVM diagnosis',title:'GC pressure, memory growth, and pauses',answer:'Heap used before GC mostly reflects allocation. Heap used after a major collection approximates the live set. A rising post-GC baseline suggests retained data; a stable baseline with frequent collections suggests high allocation or a small heap.',codeLabel:'JVM evidence and metrics',code:'jcmd <pid> GC.heap_info\njstat -gcutil <pid> 1000 20\njcmd <pid> JFR.start name=memory settings=profile duration=2m filename=memory.jfr\n\njvm_memory_used_bytes\njvm_gc_pause_seconds_count\njvm_gc_pause_seconds_sum\nprocess_resident_memory_bytes',sections:[
    {title:'Metric patterns',bullets:['Pause count and total pause time align with latency spikes: GC may contribute; inspect JFR or GC logs.','Heap returns to a stable baseline: probably allocation pressure rather than a leak.','Post-GC heap climbs across comparable load: investigate retained objects and cache or queue growth.','Process memory rises while heap is stable: inspect direct buffers, thread stacks, metaspace, and native libraries.']},
    {title:'Tool boundaries',text:'GC logs show collection history. JFR correlates allocation, GC, locks, I/O, and CPU. A heap dump shows reachable objects and retention paths but is large, sensitive, and potentially disruptive.'}
  ]},
  {id:'high-cpu',chapter:'JVM diagnosis',title:'High CPU: identify the consuming code',answer:'First confirm whether CPU belongs to application threads, garbage collection, JIT compilation, or another process. Capture evidence during the spike and compare multiple samples.',codeLabel:'High-CPU workflow',code:'# Linux per-thread CPU\ntop -H -p <pid>\n\njcmd <pid> Thread.print -l > cpu-threads.txt\njcmd <pid> JFR.start name=cpu settings=profile duration=60s filename=cpu.jfr\n\nkubectl top pod <pod> -n <namespace> --containers',sections:[
    {title:'What tools show',bullets:['top -H identifies hot native thread IDs at that instant.','Thread dumps show Java stacks; convert a native ID to hexadecimal and match nid when needed.','JFR execution samples aggregate hot methods and distinguish application, GC, and compiler activity.','Flame-graph width represents how often a stack appeared in samples.']},
    {title:'Common reasons',text:'Busy loops, retry or exception storms, pathological regex, serialization, excessive logging, high allocation driving GC, lock-free contention, decompression, encryption, or warm-up compilation.'}
  ]},
  {id:'locks-deadlock',chapter:'JVM diagnosis',title:'Lock contention and deadlock',answer:'Contention means threads wait to enter a lock and may eventually proceed. Deadlock is a cycle where each thread waits for a lock held by another, so none can progress.',codeLabel:'Repeated thread evidence',code:'jcmd <pid> Thread.print -l > threads-01.txt\njcmd <pid> Thread.print -l > threads-02.txt\njcmd <pid> JFR.start name=locks settings=profile duration=2m filename=locks.jfr',sections:[
    {title:'How to read it',bullets:['BLOCKED threads name the monitor they await and often its owner.','The same owner and waiting stack across dumps indicates sustained contention.','A detected Java deadlock appears as a lock cycle near the end of the dump.','Many TIMED_WAITING workers can be normal idle-pool behavior; inspect the stack.']},
    {title:'Typical fixes',text:'Reduce the critical section, avoid I/O while holding a lock, enforce one lock order, partition shared state, or use immutable snapshots.'}
  ]},
  {id:'downstream',chapter:'Dependency diagnosis',title:'Slow downstream service, retries, and circuit state',answer:'Measure outbound request count, latency, status, timeouts, retry attempts, and circuit state for each dependency and operation. A service can have healthy local CPU while every request waits remotely.',sections:[
    {title:'Worked interpretation',text:'Payment p99 rises to 2.8 s, checkout p99 rises to 3.0 s, and traces show almost all time in PaymentClient. Retry attempts triple request volume. Payment is slow and retries amplify load.'},
    {title:'Possible causes',bullets:['Downstream saturation or regional impairment','Connection-pool exhaustion or DNS/TLS delay','Timeout longer than caller deadline','Retrying non-transient failures','Circuit breaker opens too late','Payload or response size increased']},
    {title:'Next actions',text:'Cap attempts within the deadline, add jitter, limit concurrency, fail fast when the circuit is open, and use a truthful fallback only for optional data. Confirm both dependency and user-facing metrics recover.'}
  ]},
  {id:'kubernetes',chapter:'Platform diagnosis',title:'Kubernetes: restart, resource, and probe evidence',answer:'Start with Pod status, restart count, termination reason, events, current and previous logs, and resource usage. These distinguish application exceptions from OOM kills, probe failures, scheduling problems, and limits.',codeLabel:'Kubernetes first response',code:'kubectl get pods -n <namespace> -o wide\nkubectl describe pod <pod> -n <namespace>\nkubectl logs <pod> -n <namespace> --since=15m --timestamps\nkubectl logs <pod> -n <namespace> --previous --timestamps\nkubectl top pod <pod> -n <namespace> --containers\nkubectl get events -n <namespace> --sort-by=.metadata.creationTimestamp',sections:[
    {title:'Interpret results',bullets:['OOMKilled or exit 137: container memory crossed its limit; compare working set with heap and native memory.','Readiness failures: Pod runs but receives no Service traffic.','Liveness failures: kubelet restarts it; dependency-sensitive liveness can create restart storms.','CPU near a limit with throttling: requests may slow despite spare node CPU.','Previous logs contain output from the terminated container.']},
    {title:'Minimal images',text:'If the image lacks a shell or JDK tools, use an approved diagnostic image or Kubernetes ephemeral container. Plan access and RBAC before an incident.'}
  ]},
  {id:'slo-alerts',chapter:'Alerting',title:'SLIs, SLOs, error budgets, and actionable alerts',answer:'An SLI is the measured user outcome. An SLO is its target over a window. The error budget is the allowed bad fraction. Alert when users are affected or the budget burns too quickly, not merely when an internal value crosses an arbitrary threshold.',sections:[
    {title:'Concrete example',text:'For a 99.9% successful-request SLO over 30 days, the error budget is 0.1%. If 2% of requests fail for one hour, budget burns 20 times faster than the long-term allowance. Multi-window burn-rate alerts detect fast outages and slower degradation.'},
    {title:'Good alert content',bullets:['Affected service and user-facing SLI','Current value, threshold, and time window','Scope such as region or route','Dashboard and runbook links','Recent deployment markers','Clear owner and paging severity']},
    {title:'Avoid noise',text:'CPU at 80% may be healthy. Page when saturation threatens an SLO or immediate human action is needed; keep lower-priority signals for diagnosis or tickets.'}
  ]},
  {id:'mitigation-postincident',chapter:'Incident response',title:'Mitigate first, then prove and prevent',answer:'During active impact, restore service with the safest reversible action while preserving evidence. Root-cause analysis follows after users are protected.',sections:[
    {title:'Immediate options',bullets:['Rollback a correlated release.','Disable an optional feature or expensive path.','Route away from a failing zone or dependency.','Reduce concurrency or shed low-priority work.','Scale only when evidence shows scalable capacity is limiting.','Capture logs, traces, JFR, dumps, and deployment metadata before restart when safe.']},
    {title:'Post-incident example',text:'Cause: a missing outbound timeout held every request thread during a payment slowdown. Contributors: unbounded queue, aggressive retries, and no dependency-latency alert. Fixes: deadline-based timeout, bounded executor, retry budget, bulkhead, dashboard, failure test, and runbook drill.'},
    {title:'Verify the fix',text:'Reproduce the slowdown safely. Confirm bounded queue depth, stable memory, controlled errors, and recovery of the same success and latency SLIs that detected the incident.'}
  ]},
  {id:'tool-map',chapter:'Daily reference',title:'Choose the tool from the question',answer:'A strong investigation begins with a precise question. Each tool supplies different evidence, so select the least disruptive artifact that can confirm or reject the next hypothesis.',comparisons:[
    {title:'Prometheus + Grafana',text:'When did it start, how large is it, and which dimension is affected? Use rates, ratios, histograms, saturation, and deployment markers.'},
    {title:'OpenTelemetry trace',text:'Where did one request spend time? Inspect child spans, errors, retries, database calls, and remote duration.'},
    {title:'Structured logs',text:'What exact event occurred? Filter by trace ID, operation, version, stable error code, and instance.'},
    {title:'JFR',text:'What did the JVM do over an interval? Inspect CPU, allocation, GC, locks, parks, I/O, exceptions, and compilation.'},
    {title:'Thread dump',text:'What are threads doing now? Inspect states, stacks, owned and awaited locks, and unchanged repeated stacks.'},
    {title:'Database tools',text:'Are queries executing, lock-waiting, poorly planned, or holding transactions? Use activity, query stats, lock views, and EXPLAIN.'}
  ],callout:{title:'Interview answer pattern',text:'State the symptom, metric and expected pattern, artifact that explains it, likely causes, next confirming test, and safe mitigation.'}},
  {id:'observability-recap',chapter:'Daily reference',title:'Production troubleshooting checklist',answer:'Define customer impact, align evidence to one time window, narrow by route and release, identify the saturated or waiting resource, mitigate safely, and verify recovery with the original SLI.',sections:[
    {title:'Say this in an interview',bullets:['First confirm the user-facing failure and scope.','Compare traffic, errors, latency, and saturation over the same period.','Use a trace to locate time and metrics to decide whether the pattern is broad.','Capture a thread dump or JFR when the JVM hypothesis requires it.','Contain impact with a reversible action and preserve evidence.','Prove the cause, add a failure test, and improve the alert and runbook.']}
  ],links:[
    {label:'Spring Boot Actuator metrics',href:'https://docs.spring.io/spring-boot/reference/actuator/metrics.html'},
    {label:'OpenTelemetry Java agent',href:'https://opentelemetry.io/docs/zero-code/java/agent/'},
    {label:'Prometheus query functions',href:'https://prometheus.io/docs/prometheus/latest/querying/functions/'},
    {label:'JDK jcmd guide',href:'https://docs.oracle.com/en/java/javase/25/docs/specs/man/jcmd.html'},
    {label:'Kubernetes Pod debugging',href:'https://kubernetes.io/docs/tasks/debug/debug-application/debug-running-pod/'},
    {label:'Google SRE monitoring',href:'https://sre.google/sre-book/monitoring-distributed-systems/'}
  ]}
];

export const productionObservabilityPages = createTopicPages(specs);
