'use client';
import { createTopicPages, type TopicPageSpec } from './topic-page';
const specs: TopicPageSpec[] = [
  {id:'test-levels',chapter:'Testing strategy',title:'Unit, integration, contract, and end-to-end tests',answer:'Unit tests isolate logic and run quickly. Integration tests exercise real boundaries. Contract tests verify two services agree. End-to-end tests validate a small number of critical journeys through the deployed system.',comparisons:[{title:'Fast feedback',text:'Many focused unit and component tests explain failures well.'},{title:'Confidence at boundaries',text:'Fewer integration, contract, and end-to-end tests catch configuration and compatibility failures.'}]},
  {id:'mocking',chapter:'Testing strategy',title:'What should be mocked?',answer:'Mock slow or unavailable boundaries when testing local decisions, not value objects or the code under test. Use a real database, broker, or HTTP stub when protocol, query, transaction, or serialization behavior is the risk.',callout:{title:'Mock behavior, not implementation',text:'A test coupled to every internal method call blocks refactoring without increasing confidence.'}},
  {id:'testcontainers',chapter:'Integration tests',title:'Real dependencies with Testcontainers',answer:'Testcontainers starts disposable Docker containers from test code, giving each suite a known database, broker, or service version.',codeLabel:'JUnit example',code:'@Testcontainers\nclass OrderRepositoryTest {\n  @Container static PostgreSQLContainer<?> db =\n      new PostgreSQLContainer<>("postgres:17");\n}',sections:[{title:'Use it well',text:'Pin image versions, apply real migrations, wait for readiness, isolate test data, and reuse containers only when isolation remains explicit.'}]},
  {id:'repositories',chapter:'Integration tests',title:'Repositories and transaction behavior',answer:'Repository tests should prove constraints, mappings, queries, locking, and transaction boundaries against the production database engine when those behaviors matter.',sections:[{title:'Transactional-test trap',text:'A framework test that rolls back after each method can hide missing commits, detached lazy loading, flush-time constraint failures, and behavior across two transactions. Add tests that commit and open a new transaction.'}]},
  {id:'resilience-tests',chapter:'Failure tests',title:'Retries, idempotency, and duplicate messages',answer:'Test the ambiguous boundary: the operation succeeds but the response or acknowledgement is lost. Repeat the same idempotency key or message ID and assert one durable business effect.',flow:['Inject success + lost response','Client retries','Server deduplicates','Assert one effect'],sections:[{title:'Downstream failures',text:'Simulate timeout, reset, throttling, malformed response, and slow success. Assert the timeout budget, retry count, fallback, and emitted telemetry.'}]},
  {id:'concurrency',chapter:'Failure tests',title:'Testing concurrency',answer:'Coordinate threads to reach the contested operation together, then assert the invariant in durable state. A test that merely starts many threads without coordination may never exercise the race.',codeLabel:'Coordination sketch',code:'var ready = new CountDownLatch(workers);\nvar start = new CountDownLatch(1);\n// each task: ready.countDown(); start.await(); update();\nready.await(); start.countDown();',sections:[{title:'Repeat and inspect',text:'Run enough iterations to increase probability, but design synchronization to create the interleaving instead of relying only on repetition.'}]},
  {id:'flaky',chapter:'Test reliability',title:'Diagnosing flaky tests',answer:'Classify the nondeterminism: time, randomness, order dependence, shared state, concurrency, resource limits, or an external dependency. Reproduce with the same seed and environment, then remove the uncontrolled input.',sections:[{title:'Do not normalize retries',text:'Quarantine only to keep the pipeline useful while an owner fixes the cause. Automatic reruns can hide real races and regressions.'}]},
  {id:'cdc',chapter:'Distributed contracts',title:'Consumer-driven contract tests',answer:'A consumer publishes examples of the requests it sends and responses it needs. The provider verifies those contracts in its pipeline before deployment.',sections:[{title:'What contracts do not prove',text:'They validate interface compatibility, not full workflow correctness, production data quality, performance, or the availability of the deployed provider.'}]},
  {id:'load',chapter:'Performance testing',title:'Load, stress, spike, and soak tests',answer:'Load tests expected traffic, stress tests find the breaking point, spike tests sudden change, and soak tests reveal slow leaks or degradation. Use a realistic workload and production-like bottlenecks.',sections:[{title:'Measure outcomes',bullets:['Throughput and p50/p95/p99 latency','Errors and timeouts','CPU, memory, GC, pools, queues, and database load','Recovery after load ends']}]},
  {id:'testing-recap',chapter:'Daily recap',title:'A confidence-based test portfolio',answer:'Place tests where a failure could occur: pure logic, framework integration, data boundary, service contract, resilience behavior, and a few user journeys.',sections:[{title:'Senior answer',bullets:['Name the risk each test covers.','Use real infrastructure for behavior owned by that infrastructure.','Test failure and duplicate paths, not only success.','Keep tests deterministic and diagnosable.','Run expensive suites at a cadence matching their value.']}],links:[{label:'JUnit 5 user guide',href:'https://docs.junit.org/current/user-guide/'},{label:'Testcontainers for Java',href:'https://java.testcontainers.org/'},{label:'Pact documentation',href:'https://docs.pact.io/'}]}
];
export const testingPages=createTopicPages(specs);
